### ISSUE TITLE
Error sending message to iOS

### ISSUE THREAD

**Issue by bitterdev** [genkgo/push#1]
Hello,

i have used your library for a project. Really nice work. On Android i have no problems but on iOS i'm always getting the error message "Unpack response error" when i try to send a push notification to an iOS device id.

The error is raised from a sublibrary of your project called "apple/apn-push". 

After some researching on the internet i have seen that this error happens when a certificate file is invalid.

So i have repeated all steps to generated a valid pem file for sandbox and for production based on this guide:
http://stackoverflow.com/questions/21250510/generate-pem-file-used-to-setup-apple-push-notification

Same result "Unpack response error"

So i have tried to generate a pem file with your "generator code snippet". Both files will be generated in my file system and on my apple account. Works fine. But when i try to send the push notifcation with the new generated pem files im getting the same result "Unpack response error"

And i have a question to your "generation code". Which passphrase will be used ? Because when i setup the gateways i have to pass the password of the pem file. 

Thank you!

**Comment by frederikbosch** [comment]
@bitterdev The passphrase is the empty string. So no passphrase. Please take into account that when generating using our script, that you should use the bundle id. Our production code looks as follows.

```php
use Genkgo\Push\Certificate\Apple\Generator;
use Genkgo\Push\Certificate\Apple\PortalConnection;
use Genkgo\Push\Certificate\Apple\PushCertificate;
use Genkgo\Push\Certificate\Apple\Type;
use GuzzleHttp\Client;

$fileName = '';
$generator = new Generator(new PortalConnection(new Client(), $appleId, $password, $teamId));
try {
    $certificate = $generator->generate(new Type(Type::PRODUCTION), $application->bundleId);
    file_put_contents($fileName, (string) $certificate);
} catch (ApplicationAlreadyHasPushCertificateException $e) {
    $generator->revoke(new Type(Type::PRODUCTION), $application->bundleId);

    $certificate = $generator->generate(new Type(Type::PRODUCTION), $application->bundleId);
    file_put_contents($fileName, (string) $certificate);
}
```
